import type { Metadata } from "next";
import { getMetadataTitle } from "@/utils/metadata/title";

// Remove the export of metadata
// export const metadata: Metadata = {
//   title: "Github Profile Finder",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
